package: icecoder
version: '3.0.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/icecoder

page:
    title: ICEcoder
    perm: admin
    hasLayout: false
    icon: rex-icon fa-code
    linkAttr: { target: _blank }
requires:
    redaxo: ^5.7.0
    php:
        version: '>=7.3, <9'
        extensions: [curl]
