package: icecoder
version: '0.2.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/icecoder

page:
    title: ICEcoder
    perm: admin
    hasLayout: false
    icon: rex-icon fa-code
    linkAttr: { target: _blank }
